import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "OpenPages — AI-Generated Landing Pages, Deployed Instantly",
    description:
        "Premium, production-ready landing pages generated by AI agents and deployed to your domain in minutes. Every design is unique. Every page is stunning.",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Space+Grotesk:wght@400;500;600;700&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body>{children}</body>
        </html>
    );
}
