import ShowcaseGrid from "./components/ShowcaseGrid";

export default function Home() {
    const styles = [
        "Neobrutalist", "Swiss", "Editorial", "Glassmorphism", "Retro-Futuristic",
        "Bauhaus", "Art Deco", "Minimal", "Neumorphic", "Japandi",
        "Dark Mode", "Modernist", "Organic", "Tech Forward", "Luxury Minimal",
        "Gradient Modern", "Typography First", "Metropolitan", "Kinetic", "Neo-Geo",
        "Scandinavian", "Monochromatic", "Material", "Flat", "Corporate Pro"
    ];

    return (
        <main>
            {/* ───────── HERO ───────── */}
            <section className="hero" id="hero">
                <div className="hero-bg">
                    <div className="orb orb-1" />
                    <div className="orb orb-2" />
                    <div className="orb orb-3" />
                    <div className="grid-overlay" />
                </div>

                <nav className="nav">
                    <div className="nav-logo">
                        <span className="logo-icon">◆</span>
                        <span className="logo-text">OpenPages</span>
                    </div>
                    <div className="nav-links">
                        <a href="#showcase">Showcase</a>
                        <a href="#how-it-works">How It Works</a>
                        <a href="#pricing">Pricing</a>
                        <a href="#styles">Styles</a>
                    </div>
                    <a href="#pricing" className="nav-cta">Get Started</a>
                </nav>

                <div className="hero-content">
                    <div className="hero-badge">
                        <span className="badge-dot" />
                        AI-Powered • 25+ Design Styles • Deployed in Minutes
                    </div>
                    <h1 className="hero-title">
                        Landing Pages That
                        <br />
                        <span className="hero-gradient">Build Themselves</span>
                    </h1>
                    <p className="hero-subtitle">
                        Premium, production-ready landing pages generated by autonomous AI agents.
                        <br />
                        Every design is unique. Every page is stunning. Deployed to your domain instantly.
                    </p>
                    <div className="hero-actions">
                        <a href="#pricing" className="btn btn-primary">
                            <span>Generate Your Page</span>
                            <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
                                <path d="M4 10h12m0 0l-4-4m4 4l-4 4" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                        </a>
                        <a href="#showcase" className="btn btn-ghost">View Showcase</a>
                    </div>

                    <div className="hero-stats">
                        <div className="stat">
                            <span className="stat-number">25+</span>
                            <span className="stat-label">Design Styles</span>
                        </div>
                        <div className="stat-divider" />
                        <div className="stat">
                            <span className="stat-number">&lt;5min</span>
                            <span className="stat-label">Deploy Time</span>
                        </div>
                        <div className="stat-divider" />
                        <div className="stat">
                            <span className="stat-number">100%</span>
                            <span className="stat-label">Production Ready</span>
                        </div>
                    </div>
                </div>

                <div className="hero-scroll-indicator">
                    <div className="scroll-line" />
                </div>
            </section>

            {/* ───────── SHOWCASE ───────── */}
            <section className="showcase" id="showcase">
                <ShowcaseGrid />
            </section>

            {/* ───────── HOW IT WORKS ───────── */}
            <section className="how-it-works" id="how-it-works">
                <div className="section-container">
                    <div className="section-header">
                        <span className="section-tag">How It Works</span>
                        <h2 className="section-title">Three Agents. One Pipeline.</h2>
                        <p className="section-desc">
                            An autonomous AI orchestra generates, validates, deploys, and self-heals — without any human intervention.
                        </p>
                    </div>

                    <div className="steps">
                        <div className="step">
                            <div className="step-number">01</div>
                            <div className="step-icon">🎨</div>
                            <h3 className="step-title">Agent 1 — Generator</h3>
                            <p className="step-desc">
                                AI picks a random design style from 25+ aesthetics, generates a complete
                                Next.js landing page, then builds it locally to verify everything compiles.
                                If it fails, it auto-fixes and retries.
                            </p>
                            <div className="step-tags">
                                <span>Next.js</span>
                                <span>TypeScript</span>
                                <span>Vanilla CSS</span>
                            </div>
                        </div>

                        <div className="step-connector">
                            <svg width="48" height="48" viewBox="0 0 48 48" fill="none">
                                <path d="M12 24h24m0 0l-8-8m8 8l-8 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                        </div>

                        <div className="step">
                            <div className="step-number">02</div>
                            <div className="step-icon">🚀</div>
                            <h3 className="step-title">Agent 2 — Deployer</h3>
                            <p className="step-desc">
                                Pushes the verified code to GitHub, creates a Vercel project,
                                triggers deployment, and assigns your custom domain — all automatically.
                            </p>
                            <div className="step-tags">
                                <span>GitHub</span>
                                <span>Vercel</span>
                                <span>Custom Domain</span>
                            </div>
                        </div>

                        <div className="step-connector">
                            <svg width="48" height="48" viewBox="0 0 48 48" fill="none">
                                <path d="M12 24h24m0 0l-8-8m8 8l-8 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                        </div>

                        <div className="step">
                            <div className="step-number">03</div>
                            <div className="step-icon">🔧</div>
                            <h3 className="step-title">Agent 3 — Fixer</h3>
                            <p className="step-desc">
                                Monitors deployment. If Vercel build fails, it diagnoses the error,
                                repairs the code, re-pushes, and re-deploys automatically. Self-healing pipeline.
                            </p>
                            <div className="step-tags">
                                <span>Auto-Diagnose</span>
                                <span>Self-Healing</span>
                                <span>Discord Notify</span>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* ───────── STYLES MARQUEE ───────── */}
            <section className="styles-section" id="styles">
                <div className="section-container">
                    <div className="section-header">
                        <span className="section-tag">Design Styles</span>
                        <h2 className="section-title">25+ Unique Aesthetics</h2>
                        <p className="section-desc">
                            Every page gets a randomly selected design style. No two sites look alike.
                        </p>
                    </div>

                    <div className="marquee-wrapper">
                        <div className="marquee-track">
                            {[...styles, ...styles].map((style, i) => (
                                <span key={i} className="marquee-item">{style}</span>
                            ))}
                        </div>
                    </div>
                    <div className="marquee-wrapper marquee-reverse">
                        <div className="marquee-track">
                            {[...styles.slice(12), ...styles.slice(0, 12), ...styles.slice(12), ...styles.slice(0, 12)].map((style, i) => (
                                <span key={i} className="marquee-item">{style}</span>
                            ))}
                        </div>
                    </div>
                </div>
            </section>

            {/* ───────── PRICING ───────── */}
            <section className="pricing" id="pricing">
                <div className="section-container">
                    <div className="section-header">
                        <span className="section-tag">Pricing</span>
                        <h2 className="section-title">Simple, Transparent Pricing</h2>
                        <p className="section-desc">
                            Get a production-ready landing page with source code and deployment included.
                        </p>
                    </div>

                    <div className="pricing-grid">
                        <div className="pricing-card">
                            <div className="pricing-tier">Starter</div>
                            <div className="pricing-price">
                                <span className="price-currency">$</span>
                                <span className="price-amount">29</span>
                                <span className="price-period">/page</span>
                            </div>
                            <ul className="pricing-features">
                                <li>1 AI-generated landing page</li>
                                <li>Random design style</li>
                                <li>Full source code</li>
                                <li>Vercel deployment</li>
                                <li>Custom subdomain</li>
                            </ul>
                            <a href="#" className="btn btn-outline">Get Started</a>
                        </div>

                        <div className="pricing-card pricing-card-featured">
                            <div className="pricing-popular">Most Popular</div>
                            <div className="pricing-tier">Pro</div>
                            <div className="pricing-price">
                                <span className="price-currency">$</span>
                                <span className="price-amount">79</span>
                                <span className="price-period">/month</span>
                            </div>
                            <ul className="pricing-features">
                                <li>4 pages per month (automated)</li>
                                <li>Choose your design style</li>
                                <li>Full source code</li>
                                <li>Vercel deployment</li>
                                <li>Custom domain support</li>
                                <li>Priority Discord notifications</li>
                            </ul>
                            <a href="#" className="btn btn-primary">Get Pro</a>
                        </div>

                        <div className="pricing-card">
                            <div className="pricing-tier">Enterprise</div>
                            <div className="pricing-price">
                                <span className="price-currency">$</span>
                                <span className="price-amount">249</span>
                                <span className="price-period">/month</span>
                            </div>
                            <ul className="pricing-features">
                                <li>Unlimited pages</li>
                                <li>All 25+ design styles</li>
                                <li>Full source code</li>
                                <li>White-label deployment</li>
                                <li>Custom domain + SSL</li>
                                <li>API access</li>
                                <li>Dedicated support</li>
                            </ul>
                            <a href="#" className="btn btn-outline">Contact Us</a>
                        </div>
                    </div>
                </div>
            </section>

            {/* ───────── FOOTER ───────── */}
            <footer className="footer">
                <div className="section-container">
                    <div className="footer-top">
                        <div className="footer-brand">
                            <span className="logo-icon">◆</span>
                            <span className="logo-text">OpenPages</span>
                            <p className="footer-tagline">
                                AI-generated landing pages, deployed instantly.
                            </p>
                        </div>
                        <div className="footer-links">
                            <div className="footer-col">
                                <h4>Product</h4>
                                <a href="#showcase">Showcase</a>
                                <a href="#how-it-works">How It Works</a>
                                <a href="#pricing">Pricing</a>
                                <a href="#styles">Styles</a>
                            </div>
                            <div className="footer-col">
                                <h4>Company</h4>
                                <a href="https://zetalabs.in" target="_blank" rel="noopener noreferrer">ZetaLabs</a>
                                <a href="#">Blog</a>
                                <a href="#">Terms</a>
                                <a href="#">Privacy</a>
                            </div>
                            <div className="footer-col">
                                <h4>Connect</h4>
                                <a href="#">Discord</a>
                                <a href="https://github.com/d3osaju/OpenPages" target="_blank" rel="noopener noreferrer">GitHub</a>
                                <a href="#">Twitter / X</a>
                            </div>
                        </div>
                    </div>
                    <div className="footer-bottom">
                        <p>© 2026 OpenPages by ZetaLabs. All rights reserved.</p>
                        <p>Powered by OpenClaw Agent Orchestra</p>
                    </div>
                </div>
            </footer>
        </main>
    );
}
