"use client";

import { useState } from "react";
import showcaseData from "../../data/showcase.json";

interface Site {
    name: string;
    style: string;
    color: string;
}

const ITEMS_PER_PAGE = 10;

export default function ShowcaseGrid() {
    const [page, setPage] = useState(1);
    const totalPages = Math.ceil(showcaseData.length / ITEMS_PER_PAGE);

    const startIndex = (page - 1) * ITEMS_PER_PAGE;
    const currentSites = showcaseData.slice(startIndex, startIndex + ITEMS_PER_PAGE) as Site[];

    return (
        <div className="section-container">
            <div className="section-header">
                <span className="section-tag">Showcase</span>
                <h2 className="section-title">Every Page, a Masterpiece</h2>
                <p className="section-desc">
                    Real sites generated by our AI agents. Each one uses a different design style.
                    All deployed and live in under 5 minutes.
                </p>
            </div>

            <div className="showcase-grid">
                {currentSites.map((site) => (
                    <a
                        key={site.name}
                        className="showcase-card"
                        href={`https://${site.name}.openpages.zetalabs.in`}
                        target="_blank"
                        rel="noopener noreferrer"
                        style={{ "--card-accent": site.color } as React.CSSProperties}
                    >
                        <div className="card-preview">
                            <div className="card-browser-bar">
                                <span className="browser-dot" />
                                <span className="browser-dot" />
                                <span className="browser-dot" />
                                <span className="browser-url">{site.name}.openpages.zetalabs.in</span>
                            </div>
                            <div className="card-screen">
                                <img
                                    src={`https://image.thum.io/get/width/800/crop/800/https://${site.name}.openpages.zetalabs.in`}
                                    alt={site.name}
                                    className="screen-thumbnail"
                                    loading="lazy"
                                />
                            </div>
                        </div>
                        <div className="card-info">
                            <h3 className="card-name">{site.name}</h3>
                            <span className="card-style">{site.style}</span>
                        </div>
                        <div className="card-arrow">↗</div>
                    </a>
                ))}
            </div>

            {totalPages > 1 && (
                <div className="pagination">
                    <button
                        className="btn btn-ghost"
                        onClick={() => setPage(p => Math.max(1, p - 1))}
                        disabled={page === 1}
                    >
                        Previous
                    </button>
                    <div className="page-numbers">
                        {Array.from({ length: totalPages }).map((_, i) => (
                            <button
                                key={i}
                                className={`page-number ${page === i + 1 ? "active" : ""}`}
                                onClick={() => setPage(i + 1)}
                            >
                                {i + 1}
                            </button>
                        ))}
                    </div>
                    <button
                        className="btn btn-ghost"
                        onClick={() => setPage(p => Math.min(totalPages, p + 1))}
                        disabled={page === totalPages}
                    >
                        Next
                    </button>
                </div>
            )}
        </div>
    );
}
