import { exec } from "child_process";
import { promisify } from "util";
import fs from "fs/promises";
import path from "path";
import { Octokit } from "@octokit/rest";
import fetch from "node-fetch";

const execAsync = promisify(exec);

// Generate a random name for the new landing page
function generateSiteName() {
    const adjectives = ["rapid", "swift", "nova", "apex", "zenith", "hyper", "ultra", "lunar", "solar", "neon"];
    const nouns = ["launch", "forge", "wave", "spark", "pulse", "orbit", "flow", "nexus", "core", "grid"];
    const randomAdjective = adjectives[Math.floor(Math.random() * adjectives.length)];
    const randomNoun = nouns[Math.floor(Math.random() * nouns.length)];
    const randomNumber = Math.floor(Math.random() * 1000);
    return `${randomAdjective}-${randomNoun}-${randomNumber}`;
}

async function runOpenclaw(siteName: string, outputDir: string) {
    console.log(`Starting Openclaw generation for ${siteName}...`);
    // Define a basic prompt for Openclaw to generate a Next.js landing page
    const prompt = `Create a beautiful, modern, high-converting React landing page for a SaaS product called ${siteName}. Use Tailwind CSS for styling. Make it look premium with dark mode, glowing gradients, and smooth animations. Ensure it's a complete, standalone project.`;

    // Note: Assuming Openclaw can be invoked via WSL and output to a specific directory
    // Adjust the exact CLI arguments based on Openclaw's actual usage
    // For testing purposes, we use a mock script since Openclaw is hanging
    const command = `node ./src/lib/orchestrator/mock-openclaw.js generate --prompt "${prompt}" --output "${outputDir}"`;

    try {
        const { stdout, stderr } = await execAsync(command);
        console.log("Openclaw generation stdout:", stdout);
        if (stderr) console.error("Openclaw generation stderr:", stderr);
        return true;
    } catch (error) {
        console.error("Failed to run Openclaw:", error);
        return false;
    }
}

async function main() {
    const siteName = generateSiteName();
    const outputDir = path.join(process.cwd(), ".generated", siteName);

    console.log(`Pipeline started for: ${siteName}`);

    // 1. Generate the site using Openclaw via WSL
    const generationSuccess = await runOpenclaw(siteName, outputDir);
    if (!generationSuccess) {
        console.error("Pipeline aborted: Generation failed.");
        return;
    }

    console.log("Generation successful!");

    // 2. Create GitHub repository and push code
    const githubToken = process.env.GITHUB_TOKEN;
    if (!githubToken) {
        console.error("Pipeline aborted: GITHUB_TOKEN not found.");
        return;
    }

    const octokit = new Octokit({ auth: githubToken });
    let repoUrl = "";
    let repoFullName = "";

    try {
        const githubOrg = process.env.GITHUB_ORG;

        console.log(`Creating GitHub repository: ${siteName}`);
        // Create the repository
        let response;
        if (githubOrg) {
            response = await octokit.rest.repos.createInOrg({
                org: githubOrg,
                name: siteName,
                description: `Landing page generated by Openclaw for Openpages`,
                private: false,
            });
        } else {
            response = await octokit.rest.repos.createForAuthenticatedUser({
                name: siteName,
                description: `Landing page generated by Openclaw for Openpages`,
                private: false,
            });
        }

        repoUrl = response.data.html_url;
        repoFullName = response.data.full_name;
        const gitUrl = response.data.clone_url;
        console.log(`Repository created at: ${repoUrl}`);

        // Assuming the generated code is a complete git repository or we need to init one
        // We'll init, add, commit, and push
        console.log("Pushing code to GitHub...");
        const gitCommands = [
            `cd "${outputDir}"`,
            `git init`,
            `git add .`,
            `git commit -m "Initial commit from Openclaw"`,
            `git branch -M main`,
            `git remote add origin https://${githubToken}@github.com/${repoFullName}.git`,
            `git push -u origin main`
        ].join(" && ");

        await execAsync(gitCommands);
        console.log("Code pushed successfully.");

    } catch (error) {
        console.error("Failed to create or push to GitHub repository:", error);
        return;
    }

    // 3. Vercel deployment and domain mapping
    const vercelToken = process.env.VERCEL_TOKEN;
    if (!vercelToken) {
        console.error("Pipeline aborted: VERCEL_TOKEN not found.");
        return;
    }

    let vercelUrl = "";
    try {
        console.log("Creating Vercel project and linking GitHub repo...");
        // Create Vercel project linked to the GitHub repo
        const createProjectRes = await fetch("https://api.vercel.com/v9/projects", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${vercelToken}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                name: siteName,
                framework: "nextjs",
                gitRepository: {
                    repo: repoFullName,
                    type: "github"
                }
            })
        });

        if (!createProjectRes.ok) {
            throw new Error(`Failed to create Vercel project: ${await createProjectRes.text()}`);
        }

        const projectData = await createProjectRes.json();
        const projectId = (projectData as any).id;
        console.log(`Vercel project created: ${projectId}`);

        // Check if domain assignment is needed
        // Note: Vercel automatically creates a `<project-name>.vercel.app` domain. 
        // To add `[siteName].Openpages.Zetalabs.in`, we use the domains endpoint.
        const customDomain = `${siteName}.Openpages.Zetalabs.in`.toLowerCase();

        console.log(`Assigning domain ${customDomain} to Vercel project...`);
        const addDomainRes = await fetch(`https://api.vercel.com/v9/projects/${projectId}/domains`, {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${vercelToken}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                name: customDomain
            })
        });

        if (!addDomainRes.ok) {
            console.warn(`Warning: Failed to add custom domain. Falling back to default Vercel URL. ${await addDomainRes.text()}`);
            vercelUrl = `${siteName}.vercel.app`; // Fallback optimistic URL
        } else {
            vercelUrl = customDomain;
            console.log(`Domain assigned: ${customDomain}`);
        }

        // Since linking a repo triggers an initial silent deployment sometimes, or we can trigger it explicitly
        // For now we'll rely on Vercel's automatic deployment on repo creation/link
        // If explicit deployment is needed:
        /*
        const deployRes = await fetch("https://api.vercel.com/v13/deployments", {
          method: "POST",
          headers: { "Authorization": `Bearer ${vercelToken}`, "Content-Type": "application/json" },
          body: JSON.stringify({ name: siteName, gitSource: { repoId: ..., ref: "main", type: "github" } })
        });
        */

    } catch (error) {
        console.error("Vercel deployment failed:", error);
        return;
    }

    // 4. Update Database
    try {
        console.log("Updating local database...");
        const dbUpdateRes = await fetch("http://localhost:3000/api/websites", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                name: siteName,
                githubUrl: repoUrl,
                vercelUrl: vercelUrl,
                status: "DEPLOYED",
                screenshot: "" // Can be populated later by a screenshot service
            })
        });
        if (!dbUpdateRes.ok) throw new Error("Database API error");
        console.log("Database updated successfully.");
    } catch (error) {
        console.error("Failed to update database:", error);
    }

    // 5. Discord webhook notification logic
    const discordWebhookUrls = process.env.DISCORD_WEBHOOK_URL;
    if (discordWebhookUrls) {
        console.log("Sending Discord notification...");
        try {
            await fetch(discordWebhookUrls, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    content: `🚀 **New Openpages Site Deployed!**\n\n**Name:** ${siteName}\n**Live URL:** https://${vercelUrl}\n**GitHub:** ${repoUrl}\n\nGenerated autonomously by Openclaw.`
                })
            });
            console.log("Discord notification sent.");
        } catch (error) {
            console.error("Failed to send Discord notification:", error);
        }
    } else {
        console.log("Skipping Discord notification (DISCORD_WEBHOOK_URL not set).");
    }

    console.log(`Pipeline completed successfully for ${siteName}.`);
}

// Allow running directly
if (require.main === module) {
    main().catch(console.error);
}
